import { Inter } from 'next/font/google'
import './styles/globals.scss'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '나무트리',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        <div className="header">
          <button>로그인</button>
        </div>
          {children}
        </body>
    </html>
  )
}
